name: Greet User
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - test
      - dev
    types: [closed]
jobs:

  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '22.15.0'
      - run: whoami
      - run: npm install
      - run: npm run build
      - uses: ./
        with:
          name: 'Alice'
        id: greet
      - name: Process Greeting
        run: node dist/scripts/process-greeting.js
        env:
          GREETING: ${{ steps.greet.outputs.greeting }}

  build-docker:
    runs-on: ubuntu-latest
    needs: validate  # Ensure this job runs after the greet job
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.base.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Build Docker Image
        uses: ./dockerfile-action
        with:
          image-name: 'my-greeting-app'
          tag: 'latest'
          push: 'false'  # Set to 'true' for pushing

  return-greeting:
    runs-on: ubuntu-latest
    needs: [build-docker, greet]  # Ensure this job runs after the greet job
    steps:
      - uses: actions/checkout@v3
      - name: Return Greeting
        run: echo "Pipeline run successfully!"